app/src/main/java/com/valterc/ki2/karoo/formatters/ShiftCountTextFormatter.java, app/src/main/java/com/valterc/ki2/karoo/formatters/ShiftModeTextFormatter.java, app/src/main/java/com/valterc/ki2/karoo/views/DrivetrainSdkView.java, app/src/main/java/com/valterc/ki2/karoo/views/GearsSdkView.java, app/src/main/java/com/valterc/ki2/karoo/views/KarooTheme.java, app/src/main/java/com/valterc/ki2/karoo/views/Ki2SdkView.java, app/src/main/java/com/valterc/ki2/views/DrivetrainView.java, app/src/main/java/com/valterc/ki2/views/GearsView.java, app/src/main/res/layout/view_karoo_drivetrain.xml, app/src/main/res/layout/view_karoo_gears.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml
=> Add support for Karoo themes (dark/white); Improved custom views

app/src/main/java/com/valterc/ki2/views/GearsView.java
=> Fix crash when using single/fixed gear bike

app/src/main/java/com/valterc/ki2/input/InputManager.java, app/src/main/res/values/arrays.xml
=> Add option to pause/resume or mark lap on button hold

app/src/main/java/com/valterc/ki2/ant/AntManager.java, app/src/main/java/com/valterc/ki2/ant/connection/AntDeviceConnection.java, app/src/main/java/com/valterc/ki2/services/Ki2Service.java
=> Improve ant reliability

app/src/main/java/com/valterc/ki2/data/input/KarooKey.java, app/src/main/java/com/valterc/ki2/input/InputAdapter.java, app/src/main/java/com/valterc/ki2/input/InputManager.java, app/src/main/java/com/valterc/ki2/input/VirtualInputAdapter.java, app/src/main/java/com/valterc/ki2/karoo/hooks/RideActivityHook.java, app/src/main/res/values/arrays.xml
=> Add 'switch to map page' button option

app/src/main/java/com/valterc/ki2/Ki2Application.java, app/src/main/java/com/valterc/ki2/ant/connection/AntConnectionManager.java, app/src/main/java/com/valterc/ki2/ant/connection/AntDeviceConnection.java, app/src/main/java/com/valterc/ki2/ant/connection/handler/profile/ShimanoShiftingProfileHandler.java, app/src/main/java/com/valterc/ki2/ant/connection/handler/transport/TransportHandler.java, app/src/main/java/com/valterc/ki2/data/connection/ConnectionDataManager.java, app/src/main/java/com/valterc/ki2/data/connection/ConnectionsDataManager.java, app/src/main/java/com/valterc/ki2/data/switches/SwitchEvent.java, app/src/main/java/com/valterc/ki2/karoo/service/ConnectionFilter.java, app/src/main/java/com/valterc/ki2/karoo/service/Ki2ServiceClient.java, app/src/main/java/com/valterc/ki2/services/Ki2Service.java
- Improved reliability of ANT connection
- Improved connection handling when multiple devices exist
=> Improved ANT connection

app/src/main/java/com/valterc/ki2/fragments/devices/details/DeviceDetailsFragment.java, app/src/main/java/com/valterc/ki2/fragments/devices/details/DeviceDetailsViewModel.java
=> Fix device details when multiple devices are connected

app/src/main/java/com/valterc/ki2/karoo/battery/LowBatteryHandler.java, app/src/main/java/com/valterc/ki2/karoo/battery/LowBatteryRecord.java, app/src/main/java/com/valterc/ki2/karoo/handlers/HandlerManager.java
Improve handling new rides after a previous ride ended.
=> Fix handler ride status

app/src/main/java/com/valterc/ki2/karoo/hooks/RideActivityHook.java, app/src/main/java/com/valterc/ki2/karoo/service/ServiceClient.java, app/src/main/java/com/valterc/ki2/utils/ProcessUtils.java
=> Support switches on ride profiles with no Ki2 elements

app/src/main/java/com/valterc/ki2/data/preferences/PreferencesStore.java, app/src/main/java/com/valterc/ki2/data/preferences/PreferencesView.java, app/src/main/java/com/valterc/ki2/karoo/shifting/ShiftingAudioAlertHandler.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/preferences_global.xml, app/src/main/res/xml/preferences_audio_alerts.xml
=> Add delay between audio alerts

app/src/main/java/com/valterc/ki2/karoo/service/ServiceClient.java
=> Re-bind to service

app/src/main/java/com/valterc/ki2/ant/connection/handler/profile/ShimanoShiftingProfileHandler.java
Initialize teeth patterns for units that don't support reporting chainring information.
=> Initialize teeth patterns

app/src/main/java/com/valterc/ki2/data/device/DeviceName.java, app/src/main/java/com/valterc/ki2/data/preferences/device/DevicePreferences.java, app/src/main/java/com/valterc/ki2/data/preferences/device/DevicePreferencesView.java, app/src/main/java/com/valterc/ki2/karoo/battery/LowBatteryHandler.java
Show correct battery value when battery notification changes category.
=> Improve battery handler

app/src/main/java/com/valterc/ki2/data/audio/AudioAlertEvent.java, app/src/main/java/com/valterc/ki2/data/message/AudioAlertEventMessage.java, app/src/main/java/com/valterc/ki2/data/message/AudioAlertMessage.java, app/src/main/java/com/valterc/ki2/data/message/MessageType.java, app/src/main/java/com/valterc/ki2/data/preferences/PreferencesView.java, app/src/main/java/com/valterc/ki2/fragments/settings/overlay/OverlayThemeAdapter.java, app/src/main/java/com/valterc/ki2/karoo/Ki2Context.java, app/src/main/java/com/valterc/ki2/karoo/Ki2Module.java, app/src/main/java/com/valterc/ki2/karoo/audio/IAudioAlertManager.java, app/src/main/java/com/valterc/ki2/karoo/audio/LocalAudioAlertManager.java, app/src/main/java/com/valterc/ki2/karoo/audio/RemoteAudioAlertManager.java, app/src/main/java/com/valterc/ki2/karoo/hooks/ActivityServiceAudioAlertManagerHook.java, app/src/main/java/com/valterc/ki2/karoo/hooks/AudioAlertHook.java, app/src/main/java/com/valterc/ki2/karoo/service/messages/CustomMessageClient.java, app/src/main/java/com/valterc/ki2/karoo/shifting/ShiftingAudioAlertHandler.java, app/src/main/java/com/valterc/ki2/update/post/PostUpdateActions.java, app/src/main/java/com/valterc/ki2/update/post/actions/UpdateAudioAlertPreferences.java, app/src/main/java/com/valterc/ki2/views/preference/AudioAlertPreference.java, app/src/main/java/com/valterc/ki2/views/preference/SummaryAndValueListPreference.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/preferences_global.xml, app/src/main/res/xml/preferences_audio_alerts.xml
=> Improve audio alerts

app/src/main/java/com/valterc/ki2/karoo/datatypes/FrontGearSizeTextDataType.java, app/src/main/java/com/valterc/ki2/karoo/datatypes/FrontGearTextDataType.java, app/src/main/java/com/valterc/ki2/karoo/datatypes/FrontShiftCountTextDataType.java, app/src/main/java/com/valterc/ki2/karoo/datatypes/RearGearSizeTextDataType.java, app/src/main/java/com/valterc/ki2/karoo/datatypes/RearGearTextDataType.java, app/src/main/java/com/valterc/ki2/karoo/datatypes/RearShiftCountTextDataType.java, app/src/main/java/com/valterc/ki2/karoo/datatypes/ShiftCountTextDataType.java
Rename data types so that the title fits in Karoo single line headers
=> Rename data types

app/src/main/java/com/valterc/ki2/karoo/overlay/view/builder/OverlayViewBuilderRegistry.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactDarkGearIndexOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactDarkGearSizeOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactDarkGearSizeRatioOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactDarkOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactLightGearIndexOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactLightGearSizeOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactLightGearSizeRatioOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactLightOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactOverlayViewHolder.java, app/src/main/res/layout/view_karoo_overlay_compact.xml, app/src/main/res/values/arrays.xml
=> Add compact overlay

app/src/main/java/com/valterc/ki2/ant/AntManager.java, app/src/main/java/com/valterc/ki2/ant/AntServiceStopper.java, app/src/main/java/com/valterc/ki2/ant/connection/AntConnectionManager.java, app/src/main/java/com/valterc/ki2/ant/connection/AntDeviceConnection.java, app/src/main/java/com/valterc/ki2/data/configuration/ConfigurationStore.java, app/src/main/java/com/valterc/ki2/karoo/service/ServiceClient.java, app/src/main/java/com/valterc/ki2/services/Ki2Service.java
- Increase connection retry count
- Add ANT Service auto re-bind when service connection is closed
- Restart connections in state 'connecting' so that connection timeouts gets reset
- Decrease time in between service re-binds
Closes #156
=> Improve connection

app/src/main/java/com/valterc/ki2/karoo/overlay/view/builder/OverlayViewBuilderRegistry.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactDarkRearGearIndexOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactDarkRearGearSizeOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactDarkRearGearSizeRatioOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactLightRearGearIndexOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactLightRearGearSizeOverlayView.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/compact/CompactLightRearGearSizeRatioOverlayView.java, app/src/main/res/layout/view_karoo_overlay.xml, app/src/main/res/layout/view_karoo_overlay_compact.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
=> Add overlay themes with rear gear only

.idea/misc.xml, app/src/main/java/com/valterc/ki2/data/preferences/PreferencesView.java, app/src/main/java/com/valterc/ki2/fragments/settings/overlay/position/OverlayPositionDialogFragment.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/builder/OverlayViewBuilderEntry.java, app/src/main/java/com/valterc/ki2/karoo/overlay/view/builder/OverlayViewBuilderRegistry.java, app/src/main/res/layout/dialog_overlay_opacity.xml, app/src/main/res/layout/dialog_overlay_position.xml, app/src/main/res/values/strings.xml
=> Add overlay default position

app/src/main/AndroidManifest.xml, app/src/main/java/com/valterc/ki2/data/input/KarooKey.java, app/src/main/java/com/valterc/ki2/data/preferences/PreferencesView.java, app/src/main/java/com/valterc/ki2/input/InputAdapter.java, app/src/main/java/com/valterc/ki2/input/InputManager.java, app/src/main/java/com/valterc/ki2/input/VirtualInputAdapter.java, app/src/main/java/com/valterc/ki2/karoo/Ki2Context.java, app/src/main/java/com/valterc/ki2/karoo/screen/ScreenHelper.java, app/src/main/java/com/valterc/ki2/karoo/service/ServiceClient.java, app/src/main/java/com/valterc/ki2/services/Ki2Service.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/preferences_global.xml, app/src/main/res/xml/preferences_switches.xml
=> Turn screen on via switches

app/src/main/AndroidManifest.xml, app/src/main/java/com/valterc/ki2/data/input/KarooKey.java, app/src/main/java/com/valterc/ki2/input/InputManager.java, app/src/main/java/com/valterc/ki2/input/VirtualInputAdapter.java, app/src/main/java/com/valterc/ki2/karoo/screen/ScreenHelper.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
Add feature to take screenshot during a ride via Di2 switches.
Closes #192
=> Add screenshot feature

app/src/main/java/com/valterc/ki2/data/input/KarooKey.java, app/src/main/java/com/valterc/ki2/data/message/AudioAlertDisableMessage.java, app/src/main/java/com/valterc/ki2/data/message/AudioAlertEnableMessage.java, app/src/main/java/com/valterc/ki2/data/message/AudioAlertToggleMessage.java, app/src/main/java/com/valterc/ki2/data/message/MessageType.java, app/src/main/java/com/valterc/ki2/data/preferences/PreferencesView.java, app/src/main/java/com/valterc/ki2/input/InputManager.java, app/src/main/java/com/valterc/ki2/input/VirtualInputAdapter.java, app/src/main/java/com/valterc/ki2/karoo/audio/LocalAudioAlertManager.java, app/src/main/java/com/valterc/ki2/karoo/screen/ScreenHelper.java, app/src/main/java/com/valterc/ki2/services/Ki2Service.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/preferences_global.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_audio_alerts.xml, app/src/main/res/xml/preferences_switches.xml
- Add audio alerts general enable option
- Add switch integration to:
- Toggle (Disable/Audio) shifting audio alerts
- Single and Double beep
Closes #199
=> Audio alert option and switch integration

app/src/main/java/com/valterc/ki2/karoo/hooks/ActivityServiceActivityDataControllerClientHook.java, app/src/main/java/com/valterc/ki2/karoo/hooks/DataSyncServiceHook.java
=> Fix shifting data reporting to FIT file

app/src/main/java/com/valterc/ki2/data/input/KarooKey.java, app/src/main/java/com/valterc/ki2/input/InputManager.java, app/src/main/java/com/valterc/ki2/input/VirtualInputAdapter.java, app/src/main/java/com/valterc/ki2/karoo/audio/LocalAudioAlertManager.java, app/src/main/java/com/valterc/ki2/karoo/hooks/ActivityServiceAudioAlertManagerHook.java, app/src/main/java/com/valterc/ki2/karoo/hooks/AudioAlertHook.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/preferences_global.xml
=> Fix custom beeps

app/src/main/java/com/valterc/ki2/input/InputManager.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/preferences_global.xml
=> Improve map zoom when holding switch

app/src/main/java/com/valterc/ki2/data/preferences/PreferencesView.java, app/src/main/java/com/valterc/ki2/karoo/Ki2BroadcastReceiver.java, app/src/main/java/com/valterc/ki2/karoo/Ki2Module.java, app/src/main/java/com/valterc/ki2/karoo/hooks/RideActivityHook.java, app/src/main/res/values/preferences_global.xml, app/src/main/res/xml/preferences_general.xml
Replaced pre load with manual refreshing profile elements in the ride app.
=> Fix pre load

app/src/main/java/com/valterc/ki2/karoo/overlay/manager/BaseOverlayManager.java, app/src/main/java/com/valterc/ki2/karoo/overlay/position/PositionManager.java
=> Fix overlay position

app/src/main/java/com/valterc/ki2/karoo/Ki2ExtensionService.kt, app/src/main/java/com/valterc/ki2/karoo/datatypes/visual/GearsDetailedVisualDataType.kt, app/src/main/java/com/valterc/ki2/karoo/views/GearsDetailedExtensionView.kt, app/src/main/res/layout/view_karoo_gears_detailed.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/karoo_extension_info.xml
=> Add detailed gears datatype

app/src/main/java/com/valterc/ki2/fragments/devices/details/DeviceDetailsFragment.java, app/src/main/res/layout/dialog_accent_color.xml, app/src/main/res/layout/dialog_overlay_opacity.xml, app/src/main/res/layout/dialog_overlay_position.xml, app/src/main/res/layout/dialog_overlay_theme.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
=> Fix dialog text after Karoo language change

app/src/main/java/com/valterc/ki2/karoo/Ki2ExtensionService.kt, app/src/main/java/com/valterc/ki2/karoo/datatypes/text/ShiftCountDataType.kt, app/src/main/res/xml/karoo_extension_info.xml
=> Add shift count data type

app/src/main/java/com/valterc/ki2/karoo/Ki2ExtensionContext.kt, app/src/main/java/com/valterc/ki2/karoo/Ki2ExtensionService.kt, app/src/main/java/com/valterc/ki2/karoo/audio/AudioManager.kt, app/src/main/java/com/valterc/ki2/karoo/battery/BatteryAlertHandler.kt, app/src/main/java/com/valterc/ki2/karoo/battery/BatteryAlertRecord.kt, app/src/main/java/com/valterc/ki2/karoo/battery/BatteryAlertType.kt, app/src/main/java/com/valterc/ki2/karoo/device/KarooSensorDeviceTracking.kt, app/src/main/java/com/valterc/ki2/karoo/device/ShiftingDevice.kt
Add fallback battery alerts for users that don't add the Ki2 extension devices to Karoo sensors.
=> Battery alerts
